#!/usr/bin/env python

import re
import sys
import os
from tkinter import *

from tkinter import filedialog


window = Tk()

window.title('SRT Fix')

window.geometry("150x150")

window.config(background = "white")

def choose():
	return filedialog.askopenfilenames(initialdir = None,
										title = "Select Files",
										filetypes = (
                      ("all files" , "*.*"),
                      ("Text files", "*.txt*"),
											("SRT  files", "*.srt*")))

def dnum():
  filenames = choose()
  for filename in filenames:
    file = open(filename,'r').read()

    lines = re.split('\n',file)

    i=0
    for line in lines:
      if re.search('^\d+$',line) is not None:
        lines[i] = ''
      i+=1

    output = open(filename,'w')
    output.write("\n".join(lines))
    output.close()

def numf():
  filenames = choose()
  for filename in filenames:
    file = open(filename,'r').read()

    lines = re.split('\n',file)

    paragraphs = []

    LEN = len(lines)

    def empty(string):
      string=string.strip()
      return not string

    i = 0
    while i < LEN:
      if not empty(lines[i]):
        paragraph = []
        while not empty(lines[i]) and i!=LEN:
          paragraph.append(lines[i])
          i+=1
        paragraphs.append(paragraph)
      i+=1

    lines = []

    for i in range(len(paragraphs)):
      index = i+1
      paragraph = paragraphs[i]
      lines.append(str(index))
      for line in paragraph:
        lines.append(line)
      lines.append('')

    output = open(filename,'w')
    output.write("\n".join(lines))
    output.close()

def srt2():
  filenames = choose()
  for filename in filenames:
    file = filename
    dest = re.sub('\.srt$','.txt',file)
    os.rename(file,dest)

def txt2():
  filenames = choose()
  for filename in filenames:
    file = filename
    dest = re.sub('\.txt$','.srt',file)
    os.rename(file,dest)

DNUM = Button(window, text = 'denumberfy', command = dnum)
NUMF = Button(window, text = 'numberfy'  , command = numf)
SRT2 = Button(window, text = 'srt2txt'   , command = srt2)
TXT2 = Button(window, text = 'txt2srt'   , command = txt2)

DNUM.grid(column = 1, row = 1)
NUMF.grid(column = 1, row = 2)
SRT2.grid(column = 1, row = 3)
TXT2.grid(column = 1, row = 4)

window.mainloop()
